<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAssignProduct
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="wk-loading-mask wk-display-none">
    <div class="wk-loader"></div>
</div>
<?php
$assignedProducts = $block->getAssignedProducts();
$product = $block->getProduct();
$productType = $product->getTypeId();
$isPriceVisible = $block->isShippingCostEnableOnProPage();
?>
<?php if ($assignedProducts->getSize()):?>
<div id="product_list" class="seller-container">
    <p class="seller-container-title">Available Selling Partners for your location</p>
    <div class="seller-sub-container">
        <div class="deliver-details-section">
            <p>Sold &amp; Delivered By: <span class="seller-count"></span></p>
            <p>Expected delivery within 5 to 7 Days</p>        
        </div>
        <div id="product_list" class="wk-ap-product-list wk-ap-fieldset">            
            <?php foreach ($assignedProducts as $assignedProduct): ?>
            <?php
            $sellerDetails = $block->getSellerDetail($assignedProduct->getSellerId());
            $shopTitle = $sellerDetails->getShopTitle();
            if ($shopTitle == "") {
                $shopTitle = $sellerDetails->getShopUrl();
            }
            $shopUrl = $sellerDetails->getShopUrl();
            ?>
            <div class="main-seller-div">
                <p>
                    <span class="wk-ap-shop-title">
                            <a class="wk-ap-shop-link" title="<?= /* @noEscape */ $shopTitle; ?>"
                            target="_blank" href="<?= /* @noEscape */ $block->getUrl('marketplace/seller/profile',['shop'=>$shopUrl]); ?>">
                                <?= /* @noEscape */ $shopTitle; ?>
                            </a>
                    </span>
                </p>
                <div class=price-section>
                    <?php
                        if ($isPriceVisible) {
                            $sellerOrigin = $block->getSellerOriginPostalCode($sellerDetails->getSellerId());
                            $customerOrigin = $block->getCustomerOriginPostalCode();
                            $shippingCost = $block->getDeliveryShipCost($sellerOrigin, $customerOrigin, $product);
                            $shippingPrice = $block->getFormattedPrice($shippingCost);
                            $sellerProPrice = $block->getFormattedPrice($assignedProduct->getPrice());
                            ?>
                            <div class="price">
                                <span class="wk-ap-product-price"><?= $sellerProPrice ?></span>
                            </div>
                    <?php } ?>
                    <div class="qty">
                        <input type="number" class="wk-ap-qty input-text qty" title="<?= /* @noEscape */ __('Qty'); ?>" value="1" maxlength="12" name="qty">
                    </div>
                    <div class="add-to-cart">
                        <button data-id="<?= /* @noEscape */ $assignedProduct->getId() ?>"
                            class="wk-ap-add-to-cart action primary tocart"
                            title="<?= /* @noEscape */ __('Add to Cart'); ?>"
                            type="button">
                            <span><?= /* @noEscape */ __('Add to Cart'); ?></span>
                        </button>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>            
        </div>
    </div>
</div> 
<?php endif; ?> 
<?php if (count($assignedProducts) == 0){ ?>
    <p class="no-seller-text"><span><?= __('No seller available for your location') ?></span></p>
<?php } ?>
<script type="text/x-magento-init">
{
    "body": {
        "Webkul_MpAssignProduct/js/assignproduct": ""
    }
}
</script>
