<?php

namespace Redstage\AmcConfigurator\Setup;

use \Magento\Framework\Setup\UpgradeDataInterface;
use \Magento\Framework\Setup\ModuleContextInterface;
use \Magento\Framework\Setup\ModuleDataSetupInterface;

/**
 * Class UpgradeData
 *
 * @package Thecoachsmb\Mymodule\Setup
 */
class UpgradeData implements UpgradeDataInterface
{

    /**
     * Creates sample articles
     *
     * @param ModuleDataSetupInterface $setup
     * @param ModuleContextInterface $context
     * @return void
     */
    public function upgrade(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $setup->startSetup();

        if ($context->getVersion()
            && version_compare($context->getVersion(), '1.0.0') < 0
        ) {
           /* $tableName = $setup->getTable('amc_customer_data');

            
            $data = [
['sales_org'=>'1009','meterial_group_1'=>'20 KVA','meterial_group_3'=>'HP i 33','asset_name'=>'XII170600525','sold_to_account_name'=>'ACTIVOLT TECH SOLUTIONS PVT.LTD','sap_customer_code'=>'388994','account_name'=>'BNP INTERIORS','billing_street'=>'C/O PWC 252 VEER SAVARKAR MARGNEXT TO MAYUR BUNGLOW SHIVAJI PARK DADAR WEST','billing_city'=>'MUMBAI','postal_code'=>'400028','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2017-11-13','warranty_end_date'=>'2019-11-12','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'PCB'],
['sales_org'=>'1009','meterial_group_1'=>'160 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII101200196','sold_to_account_name'=>'BNP PARIBAS','sap_customer_code'=>'231076','account_name'=>'BNP PARIBAS','billing_street'=>'BNP PARIBAS HOUSE, 1, NORTH AVENUEMAKER MAXITY BKC, BANDRA (EAST)','billing_city'=>'MUMBAI','postal_code'=>'400051','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2011-05-23','warranty_end_date'=>'2014-05-22','amc_contract_number'=>'40696785','amc_start_date'=>'2020-06-01','amc_end_date'=>'2021-05-31','asset_status'=>'CAMC'],
['sales_org'=>'1009','meterial_group_1'=>'160 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII101200197','sold_to_account_name'=>'BNP PARIBAS','sap_customer_code'=>'231076','account_name'=>'BNP PARIBAS','billing_street'=>'BNP PARIBAS HOUSE, 1, NORTH AVENUEMAKER MAXITY BKC, BANDRA (EAST)','billing_city'=>'MUMBAI','postal_code'=>'400051','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2011-05-23','warranty_end_date'=>'2014-05-22','amc_contract_number'=>'40696785','amc_start_date'=>'2020-06-01','amc_end_date'=>'2021-05-31','asset_status'=>'CAMC'],
['sales_org'=>'1009','meterial_group_1'=>'160 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII101200207','sold_to_account_name'=>'BNP PARIBAS','sap_customer_code'=>'231076','account_name'=>'BNP PARIBAS','billing_street'=>'BNP PARIBAS HOUSE, 1, NORTH AVENUEMAKER MAXITY BKC, BANDRA (EAST)','billing_city'=>'MUMBAI','postal_code'=>'400051','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2011-05-23','warranty_end_date'=>'2014-05-22','amc_contract_number'=>'40696785','amc_start_date'=>'2020-06-01','amc_end_date'=>'2021-05-31','asset_status'=>'CAMC'],
['sales_org'=>'1009','meterial_group_1'=>'160 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII101200208','sold_to_account_name'=>'BNP PARIBAS','sap_customer_code'=>'231076','account_name'=>'BNP PARIBAS','billing_street'=>'BNP PARIBAS HOUSE, 1, NORTH AVENUEMAKER MAXITY BKC, BANDRA (EAST)','billing_city'=>'MUMBAI','postal_code'=>'400051','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2011-05-23','warranty_end_date'=>'2014-05-22','amc_contract_number'=>'40696785','amc_start_date'=>'2020-06-01','amc_end_date'=>'2021-05-31','asset_status'=>'CAMC'],
['sales_org'=>'1009','meterial_group_1'=>'160 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII101200209','sold_to_account_name'=>'BNP PARIBAS','sap_customer_code'=>'231076','account_name'=>'BNP PARIBAS','billing_street'=>'BNP PARIBAS HOUSE, 1, NORTH AVENUEMAKER MAXITY BKC, BANDRA (EAST)','billing_city'=>'MUMBAI','postal_code'=>'400051','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2011-05-23','warranty_end_date'=>'2014-05-22','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'PCB'],
['sales_org'=>'1009','meterial_group_1'=>'160 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII101200210','sold_to_account_name'=>'BNP PARIBAS','sap_customer_code'=>'231076','account_name'=>'BNP PARIBAS','billing_street'=>'BNP PARIBAS HOUSE, 1, NORTH AVENUEMAKER MAXITY BKC, BANDRA (EAST)','billing_city'=>'MUMBAI','postal_code'=>'400051','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2011-05-23','warranty_end_date'=>'2014-05-22','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'PCB'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005527256','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'NA','account_name'=>'BNP PARIBAS C/O. SHRIDHAR GOURCHANDRA SAHU','billing_street'=>'BNP PARIBAS C/O. SHRIDHAR GOURCHANDRA SAHU INDIRA NAGAR NO-2, J.N.ROAD, TRIMURTI MITRA MANDAL CHAWL, MULUND (WEST) MUMBAI','billing_city'=>'MUMBAI','postal_code'=>'400080','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-18','warranty_end_date'=>'2022-09-17','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1001','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005527604','sold_to_account_name'=>'BNP PARIBAS C/O SHUBHANKAR LENDHE','sap_customer_code'=>'NA','account_name'=>'BNP PARIBAS C/O SHUBHANKAR LENDHE','billing_street'=>'BNP PARIBAS C/O SHUBHANKAR LENDHE 203/A, GAYATRI SOCIETY, VISHNU NAGAR NR. SATYAM COLLECTION, NAVPADA, THANE (WEST). MUMBAI','billing_city'=>'MUMBAI','postal_code'=>'400602','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-20','warranty_end_date'=>'2022-10-19','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525032','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467679','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O LARSON DIASACTON SANDOR, OPP. SADHANA BHAVAN, VASAI (W), MUMBAI','billing_city'=>'MUMBAI','postal_code'=>'401201','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-28','warranty_end_date'=>'2022-09-27','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525035','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467686','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O PRIVINSON DMELLODESTINY HOUSE DONTALAO VATAR PO AGASHI TAL VASAI DIST PALGHAR VIRAR W','billing_city'=>'MUMBAI','postal_code'=>'401301','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-11-11','warranty_end_date'=>'2022-11-10','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525036','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467687','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O KRUNAL PATEL3/203, RASHMI DIVYA COMPLEX, 100FT LINK ROAD, OPP OBC BANK. VASAI EAST,','billing_city'=>'MUMBAI','postal_code'=>'401209','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-14','warranty_end_date'=>'2022-10-13','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005527281','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467703','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.RAKESH MORYE13/TUKARAM NIWAS NEW AYRE ROAD NEAR SAI BABA TEMPLE DOMBIVLI LANDMARK.NEW AYRE ROAD NEAR SAI BABA TEM','billing_city'=>'DOMBIVLI','postal_code'=>'421201','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-28','warranty_end_date'=>'2022-09-27','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005527250','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467708','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.JAIPRAKASH MELWANIOPP BLOCK 583/A SEC.25 MAHAVIR HOSPITAL OPP SAI RESIDENCY ULHASNAGAR LANDMARK.OPP SAI RESIDENCY','billing_city'=>'ULHASNAGAR','postal_code'=>'421004','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-15','warranty_end_date'=>'2022-09-14','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525007','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467763','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.RAJKUMAR THANGARAJFLAT NO.502 GARDEN VIEW APARTMENT ROYAL PALMS AAREY COLONY GOREG LANDMARK.GOREGAON EAST','billing_city'=>'MUMBAI','postal_code'=>'400065','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-15','warranty_end_date'=>'2022-09-14','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007503396','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467765','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.ABHILASHA HASMUKH KOTECHAG/ 404 MODY PARK IRANIWADI ROAD NO.3 KANDIVALI WEST LANDMARK.KADIVALI WEST','billing_city'=>'MUMBAI','postal_code'=>'400067','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-30','warranty_end_date'=>'2022-09-29','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525014','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467767','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.KIRAN VISHNU KHOT401/A WING LAXMISAGAR CHS SAINATH NAGAR MIDC ANDHERI(E) LANDMARK.ANDHERI EAST','billing_city'=>'MUMBAI','postal_code'=>'400093','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-03','warranty_end_date'=>'2022-10-02','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005527241','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467770','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.SAMEER SHAHU RANE4/5 CLEARA NIWAS RAMNAGAR TROLLY LINE ROAD BHANDUP EAST LANDMARK.BHANDUP EAST','billing_city'=>'MUMBAI','postal_code'=>'400042','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-06','warranty_end_date'=>'2022-10-05','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007503400','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467771','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.KIRAN KRISHNA WARISE604 BHAGIRATHI TOWER NR VITTHAL MANDIR KHAREGAON KALWA(W) LANDMARK.KALWA WEST','billing_city'=>'THANE','postal_code'=>'400605','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-21','warranty_end_date'=>'2022-09-20','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525017','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467850','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.HEMANT NAKUL NAIKB/302 SAMARTH SAI RESIDENCHY SAGARLI , DOMBIVLI EAST','billing_city'=>'MUMBAI','postal_code'=>'421203','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-22','warranty_end_date'=>'2022-10-21','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525022','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467861','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.MITHLESH OBAYA NAIKPLOT NO.168, ROOM NO.11 , VIJAY BHARAT C KHERWADI, BANDRA EAST NEAR NIRMAL NAGAR POLICE STATION','billing_city'=>'MUMBAI','postal_code'=>'400051','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-10','warranty_end_date'=>'2022-10-09','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525025','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467862','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.SAGAR ANANT CHAVAN13/603, SONAM MAYURESH CHS OLD GOLDEN NEST PHASE 3, MIRA HIGHWAY, MIRA ROAD EAST','billing_city'=>'THANE','postal_code'=>'401107','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-30','warranty_end_date'=>'2022-09-29','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525027','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467868','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.DeepaliDHARMSHRUSHTI APTS, FLAT-202, SEC 19C KOPARKHAIRANE NEAR SHIVASENA SHAKHA','billing_city'=>'NAVI MUMBAI','postal_code'=>'400709','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-04','warranty_end_date'=>'2022-12-03','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525028','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467876','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.SANIKA TIWARI347/A, HARHARWALA BLDG, OPP PODAR MILLS N.M.JOSHI MARG, LOWER PAREL EA','billing_city'=>'MUMBAI','postal_code'=>'400011','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-29','warranty_end_date'=>'2022-09-28','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525030','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467878','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.YOGI NIKHIL MEHTAD-214 VEENA SARASWAI CHS NEW LINK ROAD, VASAI EAST, PAL NEAR AGARWAL NAGARI','billing_city'=>'MUMBAI','postal_code'=>'401208','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-09','warranty_end_date'=>'2022-10-08','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525031','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467885','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.NAVDEEP SUKHDEV SINGHHOUSE NO.3531/14, SHREE OM KRUPA CHAWL DIGHA NEAR MUKUND COMPANY','billing_city'=>'NAVI MUMBAI','postal_code'=>'400708','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-09','warranty_end_date'=>'2022-10-08','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005527251','sold_to_account_name'=>'BNP PARIBAS GLOBAL SECURITIES','sap_customer_code'=>'467892','account_name'=>'BNP PARIBAS GLOBAL SECURITIES','billing_street'=>'C/O.JIGNESH HARIYAH.NO.1409, SILVER JYOT APATMENT 3RD FLOOR, R NO.304 KAMATGAR R ANJUR PHATA','billing_city'=>'BHIWANDI','postal_code'=>'NA','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-15','warranty_end_date'=>'2022-09-14','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'44204523111','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469519','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT. LT','billing_street'=>'C/O.SIDDHESH DUDE203 SAIDEEP APT BEHIND MAHADEV APT DEVKINANDAN STOP NEW SERVICE R KHAREGAON KALWA','billing_city'=>'MUMBAI','postal_code'=>'400605','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-28','warranty_end_date'=>'2022-12-27','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007506613','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469520','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT. LT','billing_street'=>'C/O.NIKHIL HEGDE104 VARAD LAXMI C.H.S OPP. VIDYA MANDIR SCHOOL GOPCHARPADA VIRAR EAST','billing_city'=>'MUMBAI','postal_code'=>'401305','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-22','warranty_end_date'=>'2022-12-21','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007506640','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469523','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT. LT','billing_street'=>'C/O.SAMRAT PAULBLD.NO.30 FLAT NO.102 SANSKRUTI OPP. ST. LAWRENCE SCHOOL THAKUR COMPLEX KANDIVALI EAST','billing_city'=>'MUMBAI','postal_code'=>'400101','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-28','warranty_end_date'=>'2022-12-27','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'44207503343','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469524','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT. LT','billing_street'=>'C/O.DNYANESHWAR BADGUJARC-1302 SUKUR ENCLAVE,OPP CHILDREN TRAFFIC PARK ANAND NAGAR GHODBUNDER ROAD THANE WEST','billing_city'=>'MUMBAI','postal_code'=>'400615','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-28','warranty_end_date'=>'2022-12-27','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1009','meterial_group_1'=>'120 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII160700541','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'184519','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 4UNIT NO. 601 6TH FLOOR OFF. FILM CITY ROAD, MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2016-11-13','warranty_end_date'=>'2020-11-12','amc_contract_number'=>'40751618','amc_start_date'=>'2020-11-13','amc_end_date'=>'2021-11-12','asset_status'=>'CAMC'],
['sales_org'=>'1009','meterial_group_1'=>'120 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII160700542','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'184519','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 4UNIT NO. 601 6TH FLOOR OFF. FILM CITY ROAD, MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2016-11-13','warranty_end_date'=>'2020-11-12','amc_contract_number'=>'40751618','amc_start_date'=>'2020-11-13','amc_end_date'=>'2021-11-12','asset_status'=>'CAMC'],
['sales_org'=>'1009','meterial_group_1'=>'120 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII160700543','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'184519','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 4UNIT NO. 601 6TH FLOOR OFF. FILM CITY ROAD, MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2016-11-13','warranty_end_date'=>'2020-11-12','amc_contract_number'=>'40751618','amc_start_date'=>'2020-11-13','amc_end_date'=>'2021-11-12','asset_status'=>'CAMC'],
['sales_org'=>'1009','meterial_group_1'=>'120 KVA','meterial_group_3'=>'HPE i 33','asset_name'=>'XII160700544','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'184519','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 4UNIT NO. 601 6TH FLOOR OFF. FILM CITY ROAD, MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2016-11-13','warranty_end_date'=>'2020-11-12','amc_contract_number'=>'40751618','amc_start_date'=>'2020-11-13','amc_end_date'=>'2021-11-12','asset_status'=>'CAMC'],
['sales_org'=>'1001','meterial_group_1'=>'120 KVA','meterial_group_3'=>'ISO - ISOLATION TRANSFORMER','asset_name'=>'IS16D159','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'184519','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 4UNIT NO. 601 6TH FLOOR OFF. FILM CITY ROAD, MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'NA','warranty_end_date'=>'NA','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'PCB'],
['sales_org'=>'1009','meterial_group_1'=>'15 KVA','meterial_group_3'=>'HP i 33','asset_name'=>'XII160600525','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'367904','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 45TH AND 6TH FLOOR OFF. FILM CITY ROAD MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2016-10-14','warranty_end_date'=>'2020-10-13','amc_contract_number'=>'40761234','amc_start_date'=>'2020-10-14','amc_end_date'=>'2021-10-13','asset_status'=>'PCB'],
['sales_org'=>'1009','meterial_group_1'=>'30 KVA','meterial_group_3'=>'KEOR T','asset_name'=>'XII170300234','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'367904','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 45TH AND 6TH FLOOR OFF. FILM CITY ROAD MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2017-06-26','warranty_end_date'=>'2021-06-25','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1009','meterial_group_1'=>'160 KVA','meterial_group_3'=>'KEOR HPE','asset_name'=>'XII170300240','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'367904','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 45TH AND 6TH FLOOR OFF. FILM CITY ROAD MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2017-06-26','warranty_end_date'=>'2021-06-25','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1009','meterial_group_1'=>'160 KVA','meterial_group_3'=>'KEOR HPE','asset_name'=>'XII170300241','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'367904','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'INFINITY IT PARK BUILDING NO 45TH AND 6TH FLOOR OFF. FILM CITY ROAD MALAD EAST','billing_city'=>'MUMBAI','postal_code'=>'400907','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2017-06-26','warranty_end_date'=>'2021-06-25','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005527192','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464430','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.MUSTAFA LUSSANWALA126, JB SHAH MARG, BARDANWALA BLDG, 3RD FLOOR, KHADAK, KHOJA DONGRI','billing_city'=>'MUMBAI','postal_code'=>'400009','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-22','warranty_end_date'=>'2022-10-21','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1001','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005527198','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464431','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.HEMAVATHY CFLAT # 201, COSMOS ORCHID LILLY LANE BESIDE RATNA SAGAR HOTEL KASARVADAVALI','billing_city'=>'THANE WEST','postal_code'=>'400615','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-07-23','warranty_end_date'=>'2022-07-22','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005524855','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464454','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.SEJAL SHAH1203, NEONA OPP RAYMOND SHOWROOM JAWAHARLAL NEHRU ROAD(STATION MULUND WEST','billing_city'=>'MUMBAI','postal_code'=>'400080','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-07-23','warranty_end_date'=>'2022-07-22','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442006504145','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464504','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O -ROHAN KAMBLEADDRESS : 2-B,1006, RAJ VAIBHAV NX, GANESH NAGAR, DOMBIVLI WEST ','billing_city'=>'MUMBAI','postal_code'=>'393001','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-21','warranty_end_date'=>'2022-10-20','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442003511525','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464525','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O -DINESH SAINDANEC/204, GREEN ACRES PH- I, GHODBUNDER RD, WAGHBIL NAKA, ABOVE B O B, TH NEXT TO VIJAY GALAXY TOWER','billing_city'=>'MUMBAI','postal_code'=>'400615','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-21','warranty_end_date'=>'2022-10-20','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005525019','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464629','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.PANKAJ PANDAYA WING 103 B-19 SHIVAM BUILDING OPP.GOKULDHAM MEDICAL CENTRE GOKULDHAM GOREGOAN EAST MUMBAI','billing_city'=>'MUMBAI','postal_code'=>'400063','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-18','warranty_end_date'=>'2022-09-17','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1001','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005524882','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464632','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.MAYURESH DESHMUKH601 JIGAR PALACE OPP.EVEREST TOWER SANTOSHI MATA MANDIR ROAD KALYAN WEST.','billing_city'=>'MUMBAI','postal_code'=>'421301','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'NA','warranty_end_date'=>'NA','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005524674','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464828','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O. BABITHA BABUC-6 PURNAY/301, KANCHAN PUSH, NEAR SURAJ WATER PARK, GHODBUNDER ROAD, THANE WEST','billing_city'=>'MUMBAI','postal_code'=>'400080','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-27','warranty_end_date'=>'2022-10-26','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442004508425','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464898','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.PURBANI DASE2, 104 GAURAV CITY, BEVERLY PARK MIRA ROAD (NEAR MARI GOLD 5 )','billing_city'=>'MUMBAI','postal_code'=>'401104','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-22','warranty_end_date'=>'2022-09-21','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442005524650','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464918','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O-SUNIL BAFNAB-307, PAREEN PALACE, ANAND NAGAR, OPP TO ANAND NAGAR GARDEN, DOM WEST, DINDAYAL ROAD, DOMBIVALI WEST','billing_city'=>'MUMBAI','postal_code'=>'421202','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-09-20','warranty_end_date'=>'2022-09-19','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442006504148','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'464930','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O-ANJALI TODI901,HEENA GAURAV JEWELS FILMCITY RD GOREGAON EAST MUMBAI','billing_city'=>'MUMBAI','postal_code'=>'400063','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-27','warranty_end_date'=>'2022-10-26','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442004523204','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'468918','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O PAYAL PATEL A/2 SHIVAM BLDGSATYAM SHIVAM SUNDARAM HSG. SCTY AMBADI ROAD, VASAI WEST, PALGH','billing_city'=>'PALGHAR','postal_code'=>'401202','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-14','warranty_end_date'=>'2022-10-13','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007506770','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'468936','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.KAMLESH DESAIE603 POONAM ORCHID CHS YASHWANT NAGAR VIRAR WEST','billing_city'=>'VIRAR','postal_code'=>'401303','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-16','warranty_end_date'=>'2022-12-15','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007503395','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'468937','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.AKSHAY S SHETTYPLOT NO.41 ROOM NO.C-13 SHANTI DOOTH CHS SAVARKAR NAGAR','billing_city'=>'THANE','postal_code'=>'400606','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-16','warranty_end_date'=>'2022-12-15','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007502855 ','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469135','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O. VINITHA VIJAYANA-2/202 AMBER YOG COMPLEX YRE ROAD DOMBIVLI EAST','billing_city'=>'MUMBAI','postal_code'=>'421201','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-07','warranty_end_date'=>'2022-10-06','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007506637 ','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469136','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O. ARPIT TAMHANEB5 VYAGHRESHWAR PRASAD, OPP KASTURI PLAZA, MANPADA ROA DOMBIVLI EAST','billing_city'=>'MUMBAI','postal_code'=>'421201','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-10-07','warranty_end_date'=>'2022-10-06','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007502854','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469155','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.MANGESH S BHOSALE9/ A, QURESHI MAHAL, M. M. C. ROAD, MAHIM (W)','billing_city'=>'MUMBAI','postal_code'=>'400016','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-21','warranty_end_date'=>'2022-12-20','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007506726','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469362','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O MR.SANDEEP S PRAJAPATISHIVSHAKTI CHAWL, GALLI NO 2 RD NO 33 OPP SUPER GAS COMPANY, SAVARKA WAGLE ESTATE, THANE','billing_city'=>'THANE','postal_code'=>'400604','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-28','warranty_end_date'=>'2022-12-27','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007506644','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'469578','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.PRANV DUBEYC-402 SHALIBHADRA AVENUE LINK ROAD, OPP MARTIN COMPLEX','billing_city'=>'NALASOPRA EAST','postal_code'=>'401209','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-12-29','warranty_end_date'=>'2022-12-28','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007503818','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'470604','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.SANDEEP MENDEL4/19, B1 MAHAVIR SHIKHAR, LBS ROAD VEEN NAGAR, MULUND WEST NEAR SLOKHA HOTEL','billing_city'=>'MUMBAI','postal_code'=>'400080','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-11-17','warranty_end_date'=>'2022-11-16','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007503293','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'470606','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O. MADAN MISHRA401 KALPAVRIKSHA CHS BESIDES PARLESHWAR POST OFFICE LAND MARK SUN CITY CINEMA VILE','billing_city'=>'VIKEPARLE','postal_code'=>'400057','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-11-09','warranty_end_date'=>'2022-11-08','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007503356','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'470607','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O. VINEETA JADAV161/1 SILVER HILL CHS, SHERE PUNJAB SOCIETY ANDHERI EAST MAHAKALI CAVES ROAD','billing_city'=>'ANDHERI','postal_code'=>'400093','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-11-09','warranty_end_date'=>'2022-11-08','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442007506763','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'470614','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O PRASHANT WAGHAMBARESATKAR TOWER BUILDING NO 5 ROOM 303 SAKHARAM NAGAR CHINCHPADA KALYAN EAST','billing_city'=>'THANE','postal_code'=>'421306','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2020-11-12','warranty_end_date'=>'2022-11-11','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1002','meterial_group_1'=>'1 KVA','meterial_group_3'=>'DLI- DIGITAL LI SERIES','asset_name'=>'442010518695','sold_to_account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','sap_customer_code'=>'481600','account_name'=>'BNP PARIBAS INDIA SOLUTIONS PVT.LTD','billing_street'=>'C/O.JYOTI RANJAN JALLY401 OMKAR PLAZA GOTHIVALI VILLAGE SECTOR-30','billing_city'=>'NAVI MUMBAI','postal_code'=>'400701','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2021-05-28','warranty_end_date'=>'2023-05-27','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UW'],
['sales_org'=>'1001','meterial_group_1'=>'6 KVA','meterial_group_3'=>'DIGITAL HP','asset_name'=>'MUS0501','sold_to_account_name'=>'GEOJIT BNP BARIBAS','sap_customer_code'=>'416268','account_name'=>'GEOJIT BNP BARIBAS','billing_street'=>'22-B,RAJABAHADUR BUILDINGAMABALAL DOSHI MARG,FORT','billing_city'=>'MUMBAI','postal_code'=>'400023','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2012-12-31','warranty_end_date'=>'2012-12-31','amc_contract_number'=>'40764790','amc_start_date'=>'2020-07-20','amc_end_date'=>'2021-07-19','asset_status'=>'CAMC'],
['sales_org'=>'1001','meterial_group_1'=>'3 KVA','meterial_group_3'=>'ONFINITI','asset_name'=>'V160703446','sold_to_account_name'=>'SUNDARAM BNP PARIBAS HOME FINANCE L','sap_customer_code'=>'370588','account_name'=>'SUNDARAM BNP PARIBAS','billing_street'=>'HOME FINANCE LTDHERITAGE NO 582 MG ROAD I FLOOR OPP HUKUMCHAND GHANTGHAR)','billing_city'=>'INDORE','postal_code'=>'452001','billing_region'=>'MADHYA PRADESH','warranty_start_date'=>'2016-11-14','warranty_end_date'=>'2019-11-13','amc_contract_number'=>'40799887','amc_start_date'=>'2021-04-01','amc_end_date'=>'2022-03-31','asset_status'=>'CAMC'],
['sales_org'=>'1001','meterial_group_1'=>'3 KVA','meterial_group_3'=>'HP MAX','asset_name'=>'XI110403239','sold_to_account_name'=>'SUNDARAM BNP PARIBAS FUND SERVICES','sap_customer_code'=>'202884','account_name'=>'SUNDARAM BNP PARIBAS FUND SERVICES','billing_street'=>'104 SHIVAM COMPLEXNEAR SILICON TOWER LAW GARDEN ELLISBRIDGE','billing_city'=>'AHMEDABAD','postal_code'=>'308006','billing_region'=>'GUJARAT','warranty_start_date'=>'2011-07-15','warranty_end_date'=>'2014-07-14','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UP'],
['sales_org'=>'1001','meterial_group_1'=>'6 KVA','meterial_group_3'=>'DIGITAL HP','asset_name'=>'XI110100702','sold_to_account_name'=>'SUNDARAM BNP PARIBAS FUND SERVICES','sap_customer_code'=>'237706','account_name'=>'SUNDARAM BNP PARIBAS FUND SERVICES','billing_street'=>'NO 114 1ST FLOOR COMMERCE HOUSENO 140 NAGINDAS MASTER ROAD, FORT','billing_city'=>'MUMBAI','postal_code'=>'400023','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2011-05-17','warranty_end_date'=>'2014-05-16','amc_contract_number'=>'NA','amc_start_date'=>'NA','amc_end_date'=>'NA','asset_status'=>'UP'],
['sales_org'=>'1001','meterial_group_1'=>'3 KVA','meterial_group_3'=>'ONFINITI','asset_name'=>'V150702925','sold_to_account_name'=>'SUNDARAM BNP PARIBAS HOME FINANCE L','sap_customer_code'=>'363668','account_name'=>'SUNDARAM BNP PARIBAS HOME FINANCE','billing_street'=>'J.M. ROADOPP. MODERN HIGH SCHOOL','billing_city'=>'PUNE','postal_code'=>'411001','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2016-05-20','warranty_end_date'=>'2019-01-06','amc_contract_number'=>'40799877','amc_start_date'=>'2021-04-01','amc_end_date'=>'2022-03-31','asset_status'=>'CAMC'],
['sales_org'=>'1001','meterial_group_1'=>'3 KVA','meterial_group_3'=>'HP MAX','asset_name'=>'XI110605848','sold_to_account_name'=>'SUNDARAM BNP PARIBAS', 'sap_customer_code'=>'248773','account_name'=>'SUNDARAM BNP PARIBAS HOME FINANCE L','billing_street'=>'C/O.SUNDARAM FINANCE LTD1ST FLR. PADMA-VISHWA REGENCY BEHIND SAROJ TRAVELS, NXT.TO M CANCER HOSPITAL, MUMBAI NAKA','billing_city'=>'NASIK','postal_code'=>'422001','billing_region'=>'MAHARASHTRA','warranty_start_date'=>'2011-11-07','warranty_end_date'=>'2014-11-06','amc_contract_number'=>'40799877','amc_start_date'=>'2021-04-01','amc_end_date'=>'2022-03-31','asset_status'=>'CAMC'],
];




            $setup
                ->getConnection()
                ->insertMultiple($tableName, $data);*/
        }

        $setup->endSetup();
    }
}