<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MarketplaceGstIndia
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
/**
 * @var \Magento\Sales\Block\Adminhtml\Order\View\Items $block
 */
$_order = $block->getOrder();
$gstColumns = [
    'sgst',
    'cgst',
    'igst',
    'utgst',
    'gst'
];
$mpGstHelper = $block->getData('mpGstHelper');
$isEnabled = $mpGstHelper->getConfigValue('status');
if ($isEnabled && $mpGstHelper->getCountryFromOrder($_order) != 'IN') {
    $isEnabled = false;
}
?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <?php $i = 0;
                $columns = $block->getColumns();
                $lastItemNumber = count($columns) ?>
                <?php if ($isEnabled) { ?>
                    <?php foreach ($columns as $columnName => $columnTitle):?>
                        <?php if (in_array(
                            $columnName,
                            $mpGstHelper->arrayMerge(['tax-percent', 'tax-amount'], $gstColumns)
                        )) {
                            continue;
                        } ?>
                        <?php $i++; ?>
                        <th class="col-<?= /* @noEscape */ $columnName ?>
                            <?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"
                        >
                            <span>
                                <?= /* @noEscape */ $columnTitle ?>
                            </span>
                        </th>
                        <?php if ($columnName == 'subtotal') { ?>
                            <?php foreach ($gstColumns as $columnName) { ?>
                                <?php $i++; ?>
                                <th class="col-<?= /* @noEscape */ $columnName ?>
                                    <?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"
                                >
                                    <span>
                                        <?= /* @noEscape */ $columns[$columnName] ?>
                                    </span>
                                </th>
                            <?php } ?>
                        <?php } ?>
                    <?php endforeach; ?>
                <?php } else { ?>
                    <?php foreach ($columns as $columnName => $columnTitle):?>
                        <?php if (in_array($columnName, $gstColumns)) {
                            continue;
                        }; ?>
                        <?php $i++; ?>
                        <th class="col-<?= /* @noEscape */ $columnName ?>
                            <?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"
                        >
                            <span>
                                <?= /* @noEscape */ $columnTitle ?>
                            </span>
                        </th>
                    <?php endforeach; ?>
                <?php } ?>
            </tr>
        </thead>
        <?php $_items = $block->getItemsCollection();?>
        <?php $i = 0; foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) {
                continue;
            } else {
                $i++;
            }?>
            <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
                <?= $block->getItemHtml($_item) ?>
                <?= $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
