<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php $tickets = $block->getTickets(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($tickets && count($tickets)): ?>
    <div class="table-wrapper orders-history service-ticket">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Magento ID') ?></th>

                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Ticket No') ?></th>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Ticket Status') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tickets as $ticket): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Magento ID')) ?>" class="col id"><?= /* @escapeNotVerified */ $ticket->getEntityId() ?></td>

                        <td data-th="<?= $block->escapeHtml(__('Ticket ID')) ?>" class="col id"><?= /* @escapeNotVerified */ $ticket->getSfServiceticketNo() ?></td>
                         <td data-th="<?= $block->escapeHtml(__('Ticket Status')) ?>" class="col id"><?= /* @escapeNotVerified */ $ticket->getSfServiceticketStatus() ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have no tickets.') ?></span></div>
<?php endif ?>

