<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_DelhiveryExtend
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    /** @var \Webkul\DelhiveryExtend\Block\Adminhtml\Seller\Edit\Tab\PostalCode $block */

    /** @var \Webkul\DelhiveryExtend\Block\Adminhtml\Seller\Edit\Tab\Grid\PostalCode $blockGrid */
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_DelhiveryExtend/js/seller/assign-postalcode": {
                "selectedPostalCode": <?= /* @noEscape */ $block->getSellerAssignedPostalCodeJson(); ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
<input type="hidden" name="sellerassignpostcodeid" id="in_adminassign_postal" data-form-part="customer_form" value="" />
