<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAssignProduct
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="wk-loading-mask wk-display-none">
    <div class="wk-loader"></div>
</div>
<?php
$assignedProducts = $block->updateAssignedProduct();
$product = $block->getProduct();
$productType = $product->getTypeId();
$isPriceVisible = $block->isShippingCostEnableOnProPage();
$buttonTitle = __('Update Cart');
?>
<div id="product_list" class="wk-ap-product-list wk-ap-fieldset">
  <table class="data table wk-table-product-list">
<?php if ($assignedProducts->getSize()):?>

      <thead>
        <th><?= /* @noEscape */ 'Seller' ?></th>
        <?php
        if ($isPriceVisible) { ?>
            <th><?= /* @noEscape */ 'Price' ?></th>
        <?php } ?>
        <th><?= /* @noEscape */ 'Action' ?></th>
      </thead>
      <?php
        foreach ($assignedProducts as $assignedProduct):
            $sellerDetails = $block->getSellerDetail($assignedProduct->getSellerId());
            $shopTitle = $sellerDetails->getShopTitle();
            if ($shopTitle == "") {
                $shopTitle = $sellerDetails->getShopUrl();
            }
            $shopUrl = $sellerDetails->getShopUrl();
            ?>
          <tr style="display:table-row" >
              <td class="col col wk-ap-img-col2">
                <span class="wk-ap-shop-title">
                    <a class="wk-ap-shop-link" title="<?= /* @noEscape */ $shopTitle; ?>"
                        target="_blank" href="<?= /* @noEscape */ $block->getUrl('marketplace/seller/profile', ['shop'=>$shopUrl]); ?>">
                        <?= /* @noEscape */ $shopTitle; ?>
                    </a>
                </span>
            </td>
            <?php
                if ($isPriceVisible) {
                    $sellerOrigin = $block->getSellerOriginPostalCode($sellerDetails->getSellerId());
                    $customerOrigin = $block->getCustomerOriginPostalCode();
                    $shippingCost = $block->getDeliveryShipCost($sellerOrigin, $customerOrigin, $product);
                    $shippingPrice = $block->getFormattedPrice($shippingCost);
                    $sellerProPrice = $block->getFormattedPrice($assignedProduct->getPrice());
                    ?>
                    <td class="col">
                        <div class="wk-ap-product-price"><?= /* @noEscape */ __('Product Price : ').$sellerProPrice ?></div>
                        <div class="wk-ap-product-price"><?= /* @noEscape */ __('Shipping Price : ').$shippingPrice ?></div>
                    </td>
            <?php } ?>
            <td class="col wk-ap-action-col wk-ap-add-to-cart-col">
                <input type="number" id="wk_qty" class="wk-ap-qty input-text qty"
                title="<?= /* @noEscape */ __('Qty'); ?>" value="1" maxlength="12"
                name="qty"  min="0">
                <button data-id="<?= /* @noEscape */ $assignedProduct->getId() ?>"
                    class="wk-ap-update-cart action primary tocart"
                    title="<?= /* @noEscape */ $buttonTitle; ?>"
                    type="button">
                    <span><?= /* @noEscape */ $buttonTitle; ?></span>
                </button>
            </td>
          </tr>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if (count($assignedProducts) == 0) { ?>
        <tr style="display:table-row"><td><?= __('No seller available for your location') ?></td></tr>
    <?php } ?>
    </table>
</div>
<script type="text/x-magento-init">
{
    "body": {
        "Webkul_DelhiveryExtend/js/updateAssignproduct": "",
        "Webkul_DelhiveryExtend/js/wksetQuantity":""
    }
}
</script>
