<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Weee\Block\Item\Price\Renderer */

$item = $block->getItem();
?>
<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
    <span class="price-including-tax" data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax')) ?>">
      
            <span class="cart-price">
                <?= /* @noEscape */ $block->formatPrice($block->getUnitDisplayPriceInclTax()) ?>
            </span>

    </span>
<?php endif; ?>

<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
    <span class="price-excluding-tax" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
        
        <span class="cart-price">
    
            <?= /* @noEscape */ $block->formatPrice($block->getUnitDisplayPriceExclTax()) ?>
        </span>
    </span>
<?php endif; ?>
