<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpRmaSystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    // $allRma = $block->getAllRma();
    $url = $block->getUrl("mprmasystem/customer/newrma");
    // $viewUrl = $block->getUrl("mprmasystem/customer/rma/");
    // $cancelUrl = $block->getUrl("mprmasystem/customer/cancel/");
    // $orderUrl = $block->getUrl("sales/order/view/");

    // $data = $block->jsonEncodeData([
    //             "filterUrl" => $block->getUrl("mprmasystem/rma/filter"),
    //             "sortingUrl" => $block->getUrl("mprmasystem/rma/sorting"),
    //             "confirmationLabel" => __("Confirmation"),
    //             "cancelRmaLabel" => __("Do you want to cancel RMA ?"),
    //             "type" => 1,
    //         ]);
    // ?>
<div class="wk-mprma-container">
    <!-- <div class="wk-loading-mask wk-display-none">
        <div class="wk-loader"></div>
    </div> -->
    <div class="wk-mp-rma-newrma">
        <a href="<?= $escaper->escapeUrl($url); ?>"><?= $escaper->escapeHtml(__("Request New RMA")); ?></a>
    </div>
</div>
</script>