<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="address-check-container">
    <p class="check-title">Check the Delivery Time</p>
    <div class="address-pdp-box">
        <input type="text" name=""  class="address-pincode">
        <button class="address-button">CHECK</button>
    </div>
    <div class="status-delivery">
    <p class="delivery-time delivery-day">Delivered within 5 to 7 days</p>
    <p class="sold-by-wrapper">Fulfilled By:   <span class="sold-by">XXXXX</span></p>
    </div>     
</div>
