<script>
require(["jquery"],function($) {
    //$('.page-products .product-items .actions-primary').remove();
    $('.sidebar .block-reorder .actions-toolbar .primary').remove();
    $('.block-wishlist #wishlist-sidebar .actions-primary').remove();
    $('#product-comparison .product-item-actions .actions-primary').remove();
    $('.sales-order-history .orders-history #my-orders-table .actions .order').remove();
    $('.sales-order-view .page-title-wrapper .order-actions-toolbar .order').remove();
    $('.minicart-content-wrapper #mini-cart .product-item-details .actions .primary').remove();
    //$('.cart-container #shopping-cart-table .actions-toolbar .action-edit').remove();
})
</script>
