<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MarketplaceGstIndia
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getOrder(); ?>
<?php $block->setPriceDataObject($_item) ?>
<?php $gstColumns = [
    'sgst',
    'cgst',
    'igst',
    'utgst',
    'gst'
];
$mpGstHelper = $block->getData('mpGstHelper');
$isEnabled = $mpGstHelper->getConfigValue('status');
if ($isEnabled && $mpGstHelper->getCountryFromOrder($_order) != 'IN') {
    $isEnabled = false;
}
?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php if ($isEnabled) { ?>
        <?php foreach ($columns as $columnName => $columnClass): ?>
            <?php if (!in_array($columnName, $mpGstHelper->arrayMerge(['tax-percent', 'tax-amount'], $gstColumns))) { ?>
                <?php $i++; ?>
                <td class="<?= /* @noEscape */ $columnClass ?>
                    <?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"
                >
                    <?= /* @escapeNotVerified */ $block->getColumnHtml($_item, $columnName) ?>
                </td>
                <?php if ($columnName == 'subtotal') { ?>
                    <?php foreach ($gstColumns as $columnName) { ?>
                        <td class="<?= /* @noEscape */ $columns[$columnName] ?>
                            <?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"
                        >
                            <?= /* @escapeNotVerified */ $block->getColumnHtml($_item, $columnName) ?>
                        </td>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        <?php endforeach; ?>
    <?php } else { ?>
        <?php foreach ($columns as $columnName => $columnClass): ?>
            <?php if (!in_array($columnName, $gstColumns)) { ?>
                <?php $i++; ?>
                <td class="<?= /* @noEscape */ $columnClass ?>
                    <?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"
                >
                    <?= /* @escapeNotVerified */ $block->getColumnHtml($_item, $columnName) ?>
                </td>
            <?php } ?>
        <?php endforeach; ?>
    <?php } ?>
</tr>
