<?php
/**
 * Redstage CustomerInstallation module purpose admin user can export customer data predifined CSV.
 *
 * @category: PHP
 * @package: Redstage/CustomerInstallation
 * @copyright: Copyright © 2019 Magento, Inc. All rights reserved.
 * @author: Mohit Tyagi <mtyagi@redstage.com>
 * @project: Legrand & Numeric
 * @keywords: Module Redstage_CustomerInstallation
 */
namespace Redstage\CustomerInstallation\Model\Config;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;

class SalesGroup extends AbstractSource
{

    /**
     * Retrieve All options
     *
     * @return array
     */
    public function getAllOptions()
    {
        $this->_options = [
            ['value' => '', 'label' =>	'Please Select'],
            ['value' => 'ABL', 'label' => 'AMBALA'],
            ['value' => 'ADI', 'label' => 'ADILABAD'],
            ['value' => 'ADY', 'label' => 'ADYAR'],
            ['value' => 'AGA', 'label' => 'AGRA'],
            ['value' => 'AGL', 'label' => 'ANGUL'],
            ['value' => 'AHD', 'label' => 'AHMEDNAGAR'],
            ['value' => 'AHS', 'label' => 'AHMEDABAD'],
            ['value' => 'AIZ', 'label' => 'AIZWAL'],
            ['value' => 'AJM', 'label' => 'AJMER'],
            ['value' => 'AKO', 'label' => 'AKOLA'],
            ['value' => 'ALG', 'label' => 'ALIGARH'],
            ['value' => 'ALH', 'label' => 'ALLAHABAD'],
            ['value' => 'ALW', 'label' => 'ALWAR'],
            ['value' => 'AMA', 'label' => 'AMARAVATI'],
            ['value' => 'AMB', 'label' => 'AMBIKAPUR'],
            ['value' => 'AMP', 'label' => 'AMEERPET'],
            ['value' => 'AMR', 'label' => 'AMRITSAR'],
            ['value' => 'ANG', 'label' => 'ANNA NAGAR'],
            ['value' => 'ANT', 'label' => 'ANANTHAPUR'],
            ['value' => 'APH', 'label' => 'ALAPUZHA'],
            ['value' => 'ARA', 'label' => 'ARRAH'],
            ['value' => 'ATA', 'label' => 'AGARTHALA'],
            ['value' => 'AUR', 'label' => 'AURANGABAD'],
            ['value' => 'AVD', 'label' => 'AVADI'],
            ['value' => 'AYL', 'label' => 'ARIYALUR'],
            ['value' => 'AZM', 'label' => 'AZAMGARH'],
            ['value' => 'BAR', 'label' => 'BAREILLY'],
            ['value' => 'BBS', 'label' => 'BHUBANESHWAR'],
            ['value' => 'BDR', 'label' => 'BIDAR'],
            ['value' => 'BEL', 'label' => 'BELLARY'],
            ['value' => 'BGM', 'label' => 'BELGAUM'],
            ['value' => 'BGN', 'label' => 'BONGAIGAON'],
            ['value' => 'BGT', 'label' => 'BAGALKOT'],
            ['value' => 'BHG', 'label' => 'BHAGALPUR'],
            ['value' => 'BHI', 'label' => 'BHIMAVARAM'],
            ['value' => 'BHM', 'label' => 'BEHRAMPORE'],
            ['value' => 'BHS', 'label' => 'BHOPAL'],
            ['value' => 'BHT', 'label' => 'BHATINDA'],
            ['value' => 'BHV', 'label' => 'BHAVNAGAR'],
            ['value' => 'BIJ', 'label' => 'BIJAPUR'],
            ['value' => 'BIK', 'label' => 'BIKANER'],
            ['value' => 'BIL', 'label' => 'BILASPUR'],
            ['value' => 'BJN', 'label' => 'BIJNOR'],
            ['value' => 'BLG', 'label' => 'BOLANGIR'],
            ['value' => 'BLS', 'label' => 'BANGALORE'],
            ['value' => 'BLT', 'label' => 'BALAGHAT'],
            ['value' => 'BNK', 'label' => 'BANKURA'],
            ['value' => 'BNS', 'label' => 'BANSWARA'],
            ['value' => 'BRD', 'label' => 'BARODA'],
            ['value' => 'BRH', 'label' => 'BHARUCH'],
            ['value' => 'BRM', 'label' => 'BERHAMPUR'],
            ['value' => 'BSF', 'label' => 'BIHAR SHARIF'],
            ['value' => 'BSR', 'label' => 'BALASORE'],
            ['value' => 'BUD', 'label' => 'BURDWAN'],
            ['value' => 'BUJ', 'label' => 'BHUJ'],
            ['value' => 'BUL', 'label' => 'BULANDSHAHR'],
            ['value' => 'CBS', 'label' => 'COIMBATORE'],
            ['value' => 'CDS', 'label' => 'CHANDIGARH'],
            ['value' => 'CHB', 'label' => 'COOCHBEHAR'],
            ['value' => 'CHH', 'label' => 'CHHATARPUR'],
            ['value' => 'CHN', 'label' => 'CHINDWARA'],
            ['value' => 'CHP', 'label' => 'CHANDRAPUR'],
            ['value' => 'CHS', 'label' => 'CHENNAI'],
            ['value' => 'CHT', 'label' => 'CHITRADURGA'],
            ['value' => 'CKM', 'label' => 'CHIKMAGALUR'],
            ['value' => 'CLT', 'label' => 'CALICUT'],
            ['value' => 'CTR', 'label' => 'CHITTOOR'],
            ['value' => 'CUD', 'label' => 'CUDDAPAH'],
            ['value' => 'DBG', 'label' => 'DHARBANGA'],
            ['value' => 'DGH', 'label' => 'DEOGARH'],
            ['value' => 'DHM', 'label' => 'DHARMAPURI'],
            ['value' => 'DHN', 'label' => 'DHANBAD'],
            ['value' => 'DHR', 'label' => 'DEHRADUN'],
            ['value' => 'DLG', 'label' => 'DALTENGANJ'],
            ['value' => 'DMP', 'label' => 'DIMAPUR'],
            ['value' => 'DNG', 'label' => 'DINDIGUL'],
            ['value' => 'DRG', 'label' => 'DURGAPUR'],
            ['value' => 'DUR', 'label' => 'DURG'],
            ['value' => 'DVG', 'label' => 'DAVANAGIRI'],
            ['value' => 'ECY', 'label' => 'ELECTRONIC CITY'],
            ['value' => 'EDH', 'label' => 'EAST DELHI'],
            ['value' => 'ERD', 'label' => 'ERODE'],
            ['value' => 'ETA', 'label' => 'ETAH'],
            ['value' => 'FAI', 'label' => 'FAIZABAD'],
            ['value' => 'FRB', 'label' => 'FARIDABAD'],
            ['value' => 'FRT', 'label' => 'FORT'],
            ['value' => 'GAN', 'label' => 'GANGTOK'],
            ['value' => 'GAY', 'label' => 'GAYA'],
            ['value' => 'GHZ', 'label' => 'GHAZIABAD'],
            ['value' => 'GNA', 'label' => 'GUNA'],
            ['value' => 'GON', 'label' => 'GONDA'],
            ['value' => 'GOR', 'label' => 'GORAKHPUR'],
            ['value' => 'GOS', 'label' => 'GOA'],
            ['value' => 'GUL', 'label' => 'GULBARGA'],
            ['value' => 'GUN', 'label' => 'GUNTUR'],
            ['value' => 'GUR', 'label' => 'GURGAON'],
            ['value' => 'GWL', 'label' => 'GWALIOR'],
            ['value' => 'GWS', 'label' => 'GUWAHATI'],
            ['value' => 'HAL', 'label' => 'HALDWANI'],
            ['value' => 'HAM', 'label' => 'HAMIRPUR'],
            ['value' => 'HAS', 'label' => 'HASSAN'],
            ['value' => 'HBL', 'label' => 'HUBLI'],
            ['value' => 'HDP', 'label' => 'HINDUPUR'],
            ['value' => 'HIS', 'label' => 'HISSAR'],
            ['value' => 'HOS', 'label' => 'HOSUR'],
            ['value' => 'HPT', 'label' => 'HOSPET'],
            ['value' => 'HRD', 'label' => 'HARIDWAR'],
            ['value' => 'HWR', 'label' => 'HOWRAH'],
            ['value' => 'HYS', 'label' => 'HYDERABAD'],
            ['value' => 'HZB', 'label' => 'HAZARIBAGH'],
            ['value' => 'IDU', 'label' => 'IDUKKI'],
            ['value' => 'IMP', 'label' => 'IMPHAL'],
            ['value' => 'IND', 'label' => 'INDORE'],
            ['value' => 'JAG', 'label' => 'JAGDALPUR'],
            ['value' => 'JAL', 'label' => 'JALGAON'],
            ['value' => 'JAM', 'label' => 'JAMSHEDPUR'],
            ['value' => 'JBL', 'label' => 'JABALPUR'],
            ['value' => 'JHN', 'label' => 'JHANSI'],
            ['value' => 'JLN', 'label' => 'JALANDHAR'],
            ['value' => 'JLR', 'label' => 'JALORE'],
            ['value' => 'JMM', 'label' => 'JAMMU'],
            ['value' => 'JMN', 'label' => 'JAMNAGAR'],
            ['value' => 'JOD', 'label' => 'JODHPUR'],
            ['value' => 'JOR', 'label' => 'JORHAT'],
            ['value' => 'JPN', 'label' => 'JP NAGAR'],
            ['value' => 'JPR', 'label' => 'JAJPUR ROAD'],
            ['value' => 'JPS', 'label' => 'JAIPUR'],
            ['value' => 'JUN', 'label' => 'JUNAGADH'],
            ['value' => 'JYR', 'label' => 'JEYPORE'],
            ['value' => 'KAK', 'label' => 'KAKINADA'],
            ['value' => 'KAL', 'label' => 'KALYAN'],
            ['value' => 'KAN', 'label' => 'KANNUR'],
            ['value' => 'KAR', 'label' => 'KARUR'],
            ['value' => 'KAS', 'label' => 'KASERGODE'],
            ['value' => 'KBA', 'label' => 'KORBA'],
            ['value' => 'KCH', 'label' => 'KANCHIPURAM'],
            ['value' => 'KHP', 'label' => 'KOLHAPUR'],
            ['value' => 'KHR', 'label' => 'KHARAGPUR'],
            ['value' => 'KLR', 'label' => 'KOLAR'],
            ['value' => 'KMM', 'label' => 'KHAMMAM'],
            ['value' => 'KMT', 'label' => 'KUMTA'],
            ['value' => 'KNG', 'label' => 'KANGRA'],
            ['value' => 'KNP', 'label' => 'KANPUR'],
            ['value' => 'KNW', 'label' => 'KHANDWA'],
            ['value' => 'KOL', 'label' => 'KOLLAM'],
            ['value' => 'KOS', 'label' => 'COCHIN'],
            ['value' => 'KOT', 'label' => 'KOTTAYAM'],
            ['value' => 'KRB', 'label' => 'KAROLBAGH'],
            ['value' => 'KRK', 'label' => 'KARAIKUDI'],
            ['value' => 'KRM', 'label' => 'KARIMNAGAR'],
            ['value' => 'KRN', 'label' => 'KARNAL'],
            ['value' => 'KSN', 'label' => 'KRISHNANAGAR'],
            ['value' => 'KTA', 'label' => 'KOTA'],
            ['value' => 'KTS', 'label' => 'KOLKATA'],
            ['value' => 'KUM', 'label' => 'KUMBAKONAM'],
            ['value' => 'KUR', 'label' => 'KURNOOL'],
            ['value' => 'LKM', 'label' => 'LAKHIMPUR'],
            ['value' => 'LKS', 'label' => 'LUCKNOW'],
            ['value' => 'LSR', 'label' => 'LAKHISARAI'],
            ['value' => 'LUD', 'label' => 'LUDHIANA'],
            ['value' => 'MAN', 'label' => 'MANDI'],
            ['value' => 'MAP', 'label' => 'MALAPPURAM'],
            ['value' => 'MBN', 'label' => 'MAHABOOP NAGAR'],
            ['value' => 'MDI', 'label' => 'MADIKERI'],
            ['value' => 'MDP', 'label' => 'MADANAPALLE'],
            ['value' => 'MDU', 'label' => 'MADURAI'],
            ['value' => 'MER', 'label' => 'MEERUT'],
            ['value' => 'MLD', 'label' => 'MALDA'],
            ['value' => 'MLR', 'label' => 'MANGALORE'],
            ['value' => 'MLS', 'label' => 'MALLEHSWARAM'],
            ['value' => 'MND', 'label' => 'MANDYA'],
            ['value' => 'MOR', 'label' => 'MORADABAD'],
            ['value' => 'MOT', 'label' => 'MOTHIHARI'],
            ['value' => 'MUS', 'label' => 'MUMBAI'],
            ['value' => 'MUZ', 'label' => 'MUZZAFARPUR'],
            ['value' => 'MYL', 'label' => 'MYLAPORE'],
            ['value' => 'MYS', 'label' => 'MYSORE'],
            ['value' => 'NAG', 'label' => 'NAGERCOIL'],
            ['value' => 'NAN', 'label' => 'NANDED'],
            ['value' => 'NAS', 'label' => 'NASIK'],
            ['value' => 'NDS', 'label' => 'NEW DELHI'],
            ['value' => 'NEL', 'label' => 'NELLORE'],
            ['value' => 'NEY', 'label' => 'NEYVELI'],
            ['value' => 'NGP', 'label' => 'NAGAPATTINAM'],
            ['value' => 'NGS', 'label' => 'NAGPUR'],
            ['value' => 'NIZ', 'label' => 'NIZAMABAD'],
            ['value' => 'NLD', 'label' => 'NALGONDA'],
            ['value' => 'NLP', 'label' => 'NORTH LAKIMPUR'],
            ['value' => 'NMK', 'label' => 'NAMAKKAL'],
            ['value' => 'NOI', 'label' => 'NOIDA'],
            ['value' => 'ONG', 'label' => 'ONGOLE'],
            ['value' => 'OTY', 'label' => 'OOTY'],
            ['value' => 'PAL', 'label' => 'PALGHAT'],
            ['value' => 'PAS', 'label' => 'PATNA'],
            ['value' => 'PAT', 'label' => 'PATHINAMTHITTA'],
            ['value' => 'PDK', 'label' => 'PUDUKOTAI'],
            ['value' => 'PDY', 'label' => 'PONDICHERRY'],
            ['value' => 'PIT', 'label' => 'PITAMPURA'],
            ['value' => 'PKR', 'label' => 'PAKUR'],
            ['value' => 'PLP', 'label' => 'PALANPUR'],
            ['value' => 'PNH', 'label' => 'PANCHKULA'],
            ['value' => 'PPR', 'label' => 'PIMPRI'],
            ['value' => 'PRY', 'label' => 'PARRYS'],
            ['value' => 'PTL', 'label' => 'PATIALA'],
            ['value' => 'PUR', 'label' => 'PURNEA'],
            ['value' => 'PUS', 'label' => 'PUNE'],
            ['value' => 'RAI', 'label' => 'RAIPUR'],
            ['value' => 'RAJ', 'label' => 'RAJKOT'],
            ['value' => 'RAS', 'label' => 'RANCHI'],
            ['value' => 'RAT', 'label' => 'RATLAM'],
            ['value' => 'RCH', 'label' => 'RAICHUR'],
            ['value' => 'RGA', 'label' => 'RAYAGADA'],
            ['value' => 'RJM', 'label' => 'RAJAHMUNDRY'],
            ['value' => 'RKL', 'label' => 'ROURKELA'],
            ['value' => 'RND', 'label' => 'RAMNAD'],
            ['value' => 'RTG', 'label' => 'RATNAGIRI'],
            ['value' => 'RTK', 'label' => 'ROHTAK'],
            ['value' => 'SAM', 'label' => 'SAMBALPUR'],
            ['value' => 'SAS', 'label' => 'SASARAM'],
            ['value' => 'SAT', 'label' => 'SATNA'],
            ['value' => 'SCR', 'label' => 'SILCHAR'],
            ['value' => 'SDI', 'label' => 'SOUTH DELHI'],
            ['value' => 'SDL', 'label' => 'SHADOL'],
            ['value' => 'SGN', 'label' => 'SRIGANGA NAGAR'],
            ['value' => 'SGR', 'label' => 'SAGAR'],
            ['value' => 'SHL', 'label' => 'SHILLONG'],
            ['value' => 'SHM', 'label' => 'SHIMOGA'],
            ['value' => 'SHP', 'label' => 'SAHARANPUR'],
            ['value' => 'SHS', 'label' => 'SAHARSA'],
            ['value' => 'SIL', 'label' => 'SILIGURI'],
            ['value' => 'SIV', 'label' => 'SIVAKASI'],
            ['value' => 'SIW', 'label' => 'SIWAN'],
            ['value' => 'SKK', 'label' => 'SRIKAKULAM'],
            ['value' => 'SLM', 'label' => 'SALEM'],
            ['value' => 'SML', 'label' => 'SHIMLA'],
            ['value' => 'SNG', 'label' => 'SANGLI'],
            ['value' => 'SNR', 'label' => 'SANGA REDDY'],
            ['value' => 'SOL', 'label' => 'SOLAPUR'],
            ['value' => 'SPT', 'label' => 'SULURPET'],
            ['value' => 'SRI', 'label' => 'SRINAGAR'],
            ['value' => 'STL', 'label' => 'SALT LAKE'],
            ['value' => 'SUR', 'label' => 'SURAT'],
            ['value' => 'TAM', 'label' => 'TAMBARAM'],
            ['value' => 'TEZ', 'label' => 'TEZPUR'],
            ['value' => 'THY', 'label' => 'TRICHY'],
            ['value' => 'TIR', 'label' => 'TIRUPATHI'],
            ['value' => 'TJR', 'label' => 'TANJORE'],
            ['value' => 'TMK', 'label' => 'TUMKUR'],
            ['value' => 'TNG', 'label' => 'TNAGAR'],
            ['value' => 'TNI', 'label' => 'THENI'],
            ['value' => 'TRN', 'label' => 'TIRUNELVELI'],
            ['value' => 'TRP', 'label' => 'TIRUPUR'],
            ['value' => 'TRS', 'label' => 'TRISSUR'],
            ['value' => 'TRV', 'label' => 'TRIVANDRUM'],
            ['value' => 'TSK', 'label' => 'TINSUKIA'],
            ['value' => 'TUT', 'label' => 'TUTICORIN'],
            ['value' => 'UDP', 'label' => 'UDAIPUR'],
            ['value' => 'UDU', 'label' => 'UDUMALPET'],
            ['value' => 'UPI', 'label' => 'UDIPI'],
            ['value' => 'VAP', 'label' => 'VAPI'],
            ['value' => 'VAR', 'label' => 'VARANASI'],
            ['value' => 'VAS', 'label' => 'VASHI'],
            ['value' => 'VJA', 'label' => 'VIJAYAWADA'],
            ['value' => 'VLP', 'label' => 'VILLUPURAM'],
            ['value' => 'VLR', 'label' => 'VELLORE'],
            ['value' => 'VSK', 'label' => 'VISHAKAPATNAM'],
            ['value' => 'WAR', 'label' => 'WARANGAL'],
            ['value' => 'WYN', 'label' => 'WAYANAD'],
            ['value' => 'YTL', 'label' => 'YOVATMAL']
        ];

        return $this->_options;
    }

    /**
     * Retrieve option array
     *
     * @return array
     */
    public function getOptionArray()
    {
      return $this->getAllOptions();
    }
}
