<?php /** * Webkul Software. * * @category Webkul * @package Webkul_MarketplaceGstIndia * @author Webkul * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com) * @license https://store.webkul.com/license.html */ /** * @var \Webkul\MarketplaceGstIndia\Block\Customer\Widget\Gstin $block */ ?> <div class="field field-name-gstin"><label class="label" for="<?= $block->escapeHtml('gstin') ?>"><span><?= $block->escapeHtml(__('GSTIN')) ?></span></label> <div class="control"><input type="text" id="<?= $block->escapeHtml('gstin') ?>" name="<?= $block->escapeHtml('gstin') ?>" value="<?= $block->escapeHtml($block->getValue()) ?>" title="<?= $block->escapeHtml(__('GSTIN')) ?>" class="input-text" ></div></div><script type="text/x-magento-init">
    {
        "*": {
            "Webkul_MarketplaceGstIndia/js/gstin": {}
        }
    }</script>