<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Srvices\Block\SrvicesForm $block */
?>
<?php $calltype = $block->getValueFromMultipleFields();?>
<form class="form services"
      action="#"
      id="services-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <div class="field note no-label"></div>
        <div class="field product_serial_number required">
            <label class="label" for="product_serial_number"><span><?= $block->escapeHtml(__('Product Serial Number')) ?></span></label>
            <div class="control">
                <input name="product_serial_number" id="product_serial_number" title="<?= $block->escapeHtmlAttr(__('Product Serial Number')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field person_logged_name required">
            <label class="label" for="person_logged_name"><span><?= $block->escapeHtml(__('Contact Person')) ?></span></label>
            <div class="control">
                <input name="person_logged_name" id="person_logged_name" title="<?= $block->escapeHtmlAttr(__('Contact Person')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field customer_company_name required">
            <label class="label" for="customer_company_name"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
            <div class="control">
                <input name="customer_company_name" id="customer_company_name" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field customer_address required">
            <label class="label" for="customer_address"><span><?= $block->escapeHtml(__('Customer Address')) ?></span></label>
            <div class="control">
                <textarea name="customer_address" id="customer_address" title="<?= $block->escapeHtmlAttr(__('Customer Address')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <div class="field pincode required">
            <label class="label" for="pincode"><span><?= $block->escapeHtml(__('Pincode')) ?></span></label>
            <div class="control">
                <input name="pincode" id="pincode" title="<?= $block->escapeHtmlAttr(__('Pincode')) ?>" class="input-text" type="text" data-validate="{required:true,'validate-number':true, 'minlength':6, 'maxlength':6}"/>
            </div>
        </div>
        <div class="field mobile required">
            <label class="label" for="mobile"><span><?= $block->escapeHtml(__('Mobile')) ?></span></label>
            <div class="control">
                <input name="mobile" id="mobile" title="<?= $block->escapeHtmlAttr(__('Mobile')) ?>" class="input-text" type="text"  data-validate="{required:true, 'validate-number':true, 'minlength':10, 'maxlength':10}" />
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field call_type required">
            <label class="label" for="call_type"><span><?= $block->escapeHtml(__('Call Type')) ?></span></label>
            <div class="control">
                <select id="edit-call-type" name="call_type" data-validate="{required:true}">
                    <option value="" selected="" hidden=""><?php echo __('Call Type') ?></option>
                    <?php foreach($calltype as $callData){ ?>
                    <option value="<?= $callData['service_calltype'];?>"><?= $callData['service_calltype'];?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="field remarks required">
            <label class="label" for="remarks"><span><?= $block->escapeHtml(__('Remark')) ?></span></label>
            <div class="control">
                <textarea name="remarks" id="remarks" title="<?= $block->escapeHtmlAttr(__('Remark')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary" id="submit-service" >
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<?php 
$ajaxurl = $block->getFormAction();
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Redstage_Services/js/servicesajax": {
                    "ServiceUrl": "<?php echo $ajaxurl; ?>"
                }
            }
        }
</script>