<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
        <?php
            echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('menu-support')
            ->toHtml();
        ?>
    </ul>
</nav>
<script type="text/javascript">
    require([
        "jquery",
        "domReady!"
    ], function ($) {
        
        if ($(".custommenu-block").parent().is("div")) {
            $(".custommenu-block").unwrap();
        }
        if ($(".custommenu-block").parent().is("div")) {
            $("#suez-custommenu-block").unwrap();
        }
        if ($(".custommenu-block").parent().is("div")) {
            $("#suez-custommenu-block").unwrap();
        }

    });
</script>
